feat: rate limiting/resource policies (#194)

diff --git a/.github/workflows/docs-build.yaml b/.github/workflows/docs-build.yaml
--- a/.github/workflows/docs-build.yaml
+++ b/.github/workflows/docs-build.yaml
@@ -18,8 +18,25 @@ jobs:
         with:
           node-version: "20"
 
+      - name: Set up Go
+        uses: actions/setup-go@v5
+        with:
+          go-version: "^1.22.4"
+
       - name: Install dependencies
         run: |
+          go install github.com/swaggo/swag/cmd/swag@latest
           yarn install
+          # bash gen.sh
           npm run build
         working-directory: ./docs-source
+
+      # - name: Check for uncommitted changes
+      #   run: |
+      #     if [ -n "$(git status --porcelain)" ]; then
+      #       echo "Uncommitted changes detected. Failing the build."
+      #       git status
+      #       exit 1
+      #     else
+      #       echo "No changes detected."
+      #     fi
