feat: building towards a zero trust microservices architecture (#165)

diff --git a/.github/workflows/js-client-example.yaml b/.github/workflows/js-client-example.yaml
--- a/.github/workflows/js-client-example.yaml
+++ b/.github/workflows/js-client-example.yaml
@@ -36,5 +36,15 @@ jobs:
             sleep 1
           done
 
-          node ./dist/index.js
+          sleep 2
+
+          set -e
+          (
+            node ./dist/index.js
+          ) || (
+            echo "Node.js script failed, running docker commands for diagnostics..."
+            docker ps
+            docker logs singulatron-backend
+            exit 1
+          )
         working-directory: ./clients/js/client-example
