feat: check for client diffs in CI (#192)

diff --git a/.github/workflows/js-client-build.yaml b/.github/workflows/js-client-build.yaml
--- a/.github/workflows/js-client-build.yaml
+++ b/.github/workflows/js-client-build.yaml
@@ -1,4 +1,4 @@
-name: Build @singulatron/client
+name: Build JS/TS clients
 
 on:
   push:
@@ -18,7 +18,36 @@ jobs:
         with:
           node-version: "20"
 
-      - name: Link and build
+      - name: Set up Go
+        uses: actions/setup-go@v5
+        with:
+          go-version: "^1.22.4"
+
+      - name: Generate
         run: |
-          bash link_local.sh
+          go install github.com/swaggo/swag/cmd/swag@latest
+          npm install @openapitools/openapi-generator-cli -g
+          bash gen.sh
         working-directory: ./clients/js
+
+      - name: Build TS client
+        run: |
+          npm install
+          npm run build
+        working-directory: ./clients/js/client
+
+      - name: Build Node client
+        run: |
+          npm install
+          npm run build
+        working-directory: ./clients/js/node
+
+      - name: Check for uncommitted changes
+        run: |
+          if [ -n "$(git status --porcelain)" ]; then
+            echo "Uncommitted changes detected. Failing the build."
+            git status
+            exit 1
+          else
+            echo "No changes detected."
+          fi
