fix

diff --git a/.github/workflows/js-client-build.yaml b/.github/workflows/js-client-build.yaml
--- a/.github/workflows/js-client-build.yaml
+++ b/.github/workflows/js-client-build.yaml
@@ -18,7 +18,32 @@ jobs:
         with:
           node-version: "20"
 
+      - name: Set up Go
+        uses: actions/setup-go@v5
+        with:
+          go-version: "^1.22.4"
+
       - name: Link and build
         run: |
-          bash link_local.sh
+          go install github.com/swaggo/swag/cmd/swag@latest
+          npm install @openapitools/openapi-generator-cli -g
+          bash gen.sh
+
+          cd client
+          npm install
+          npm run build
+          cd ..
+
+          cd node
+          npm install
+          npm run build
         working-directory: ./clients/js
+
+      - name: Check for uncommitted changes
+        run: |
+          if [ -n "$(git status --porcelain)" ]; then
+            echo "Uncommitted changes detected. Failing the build."
+            exit 1
+          else
+            echo "No changes detected."
+          fi
